/**
 * pb-eprod-1 — EPROD AP Cycle · LIVE RUN page.
 *
 * The end-to-end demo surface for Enterprise Products Partners:
 *
 *   1. Drop an invoice/PO/MSA/quote/tariff/JIB into the dropzone, or click
 *      a sample document.
 *   2. POST to /api/v1/eprod/cycle-start as multipart.
 *   3. Browser opens an SSE stream and renders the 5–6 stage timeline:
 *      ▸ extract · classify · validate · (HITL gate) · write_back · report
 *   4. Live validation findings appear as they're produced.
 *   5. If a HITL gate fires, the page shows the approve/reject banner.
 *   6. On completion, a final card appears with "Download Audit Report PDF".
 *
 * The PDF is generated by `backend/services/eprod_report_pdf.py` and served
 * via GET /api/v1/eprod/report/{cycle_id}.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1';

// ─────────────── types ───────────────

type StageId = 'extract' | 'classify' | 'validate' | 'write_back' | 'report';

interface StageState {
  id:     StageId;
  label:  string;
  status: 'pending' | 'running' | 'done' | 'error';
  ms?:    number;
  summary?: string;
}

interface Finding {
  rule:      string;
  detail:    string;
  severity:  'low' | 'medium' | 'high' | 'critical';
  category?: string;
  expected?: string;
  actual?:   string;
}

interface HitlRequired {
  request_id:      string;
  cycle_id:        string;
  agent:           string;
  gate:            string;
  severity:        'low' | 'medium' | 'high' | 'critical';
  reason:          string;
  proposed_action: string;
}

interface HitlDecided {
  request_id: string;
  decision:   'approve' | 'reject' | 'timeout' | 'missing';
  reviewer:   string;
  comment:    string;
  decided_at: number;
}

interface CycleReport {
  report_id:        string;
  cycle_id:         string;
  doc_type:         string;
  vendor?:          string;
  amount?:          number;
  status:           string;
  findings_count:   number;
  hitl_required:    boolean;
  hitl_decision?:   string;
  audit_lens_event_id?: string;
  report_pdf_url?:  string;
}

interface SampleFile {
  name:        string;
  label:       string;
  doc_type:    string;
  size_bytes:  number;
  demo_path:   string;
}

const INITIAL_STAGES: StageState[] = [
  { id: 'extract',    label: 'Extract Document',         status: 'pending' },
  { id: 'classify',   label: 'Classify + Route',         status: 'pending' },
  { id: 'validate',   label: 'Validate (MSA / FERC / AFE)', status: 'pending' },
  { id: 'write_back', label: 'Queue ERP Write-Back',     status: 'pending' },
  { id: 'report',     label: 'Emit Audit Report (PDF)',  status: 'pending' },
];

// ─────────────── main component ───────────────

export default function RunEprodCyclePage() {
  const [stages, setStages]               = useState<StageState[]>(INITIAL_STAGES);
  const [findings, setFindings]           = useState<Finding[]>([]);
  const [cycleReport, setCycleReport]     = useState<CycleReport | null>(null);
  const [cycleId, setCycleId]             = useState<string | null>(null);
  const [running, setRunning]             = useState(false);
  const [halted, setHalted]               = useState<{ reason: string } | null>(null);
  const [errorMsg, setErrorMsg]           = useState<string | null>(null);
  const [hitl, setHitl]                   = useState<HitlRequired | null>(null);
  const [hitlDecision, setHitlDecision]   = useState<HitlDecided | null>(null);
  const [hitlBusy, setHitlBusy]           = useState(false);
  const [sampleFiles, setSampleFiles]     = useState<SampleFile[]>([]);

  const abortRef = useRef<AbortController | null>(null);

  // ─── load sample files on mount ───
  useEffect(() => {
    fetch(`${API_BASE_URL}/eprod/sample-files`)
      .then((r) => (r.ok ? r.json() : { files: [] }))
      .then((d) => setSampleFiles(d.files ?? []))
      .catch(() => setSampleFiles([]));
  }, []);

  // ─── reset ───
  const reset = useCallback(() => {
    setStages(INITIAL_STAGES);
    setFindings([]);
    setCycleReport(null);
    setCycleId(null);
    setHalted(null);
    setErrorMsg(null);
    setHitl(null);
    setHitlDecision(null);
    setHitlBusy(false);
  }, []);

  // ─── decide HITL ───
  const decideHitl = useCallback(async (decision: 'approve' | 'reject') => {
    if (!hitl) return;
    setHitlBusy(true);
    try {
      const r = await fetch(
        `${API_BASE_URL}/eprod/hitl/${encodeURIComponent(hitl.request_id)}/${decision}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ reviewer: 'J. Patchett (AP Manager)', comment: '' }),
        },
      );
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
    } catch (e: any) {
      setErrorMsg(`HITL decision failed: ${e.message}`);
    } finally {
      setHitlBusy(false);
    }
  }, [hitl]);

  // ─── SSE handler ───
  const handleEvent = useCallback((event: string, data: any) => {
    switch (event) {
      case 'cycle_start':
        setCycleId(data.cycle_id);
        break;

      case 'stage_start':
        setStages((prev) => prev.map((s) =>
          s.id === data.stage_id ? { ...s, status: 'running' } : s,
        ));
        break;

      case 'stage_done':
        setStages((prev) => prev.map((s) =>
          s.id === data.stage_id ? { ...s, status: 'done', ms: data.ms, summary: data.summary } : s,
        ));
        break;

      case 'finding_emitted':
        setFindings((prev) => [...prev, {
          rule:     data.rule,
          detail:   data.detail,
          severity: data.severity,
          category: data.category,
          expected: data.expected,
          actual:   data.actual,
        }]);
        break;

      case 'hitl_required':
        setHitl(data as HitlRequired);
        break;

      case 'hitl_decided':
        setHitlDecision(data as HitlDecided);
        if (data.decision !== 'approve') {
          // pipeline halts after this — wait for cycle_halted
        }
        break;

      case 'cycle_done':
        setCycleReport(data.report ?? null);
        setRunning(false);
        break;

      case 'cycle_halted':
        setHalted({ reason: data.reason });
        setRunning(false);
        // Mark any pending stages as error
        setStages((prev) => prev.map((s) =>
          s.status === 'pending' || s.status === 'running' ? { ...s, status: 'error' } : s,
        ));
        break;
    }
  }, []);

  // ─── parse SSE stream ───
  const consumeStream = useCallback(async (response: Response) => {
    if (!response.body) throw new Error('No SSE body');
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      // SSE frames are separated by blank lines (\n\n)
      const frames = buffer.split('\n\n');
      buffer = frames.pop() || '';
      for (const frame of frames) {
        const lines = frame.split('\n');
        let event = 'message';
        let dataLine = '';
        for (const line of lines) {
          if (line.startsWith('event:')) event = line.slice(6).trim();
          else if (line.startsWith('data:')) dataLine += line.slice(5).trim();
        }
        if (!dataLine) continue;
        try {
          const data = JSON.parse(dataLine);
          handleEvent(event, data);
        } catch (e) {
          console.warn('SSE parse error', e, dataLine);
        }
      }
    }
  }, [handleEvent]);

  // ─── start a cycle ───
  const startCycle = useCallback(async (file: File) => {
    reset();
    setRunning(true);
    const fd = new FormData();
    fd.append('file', file);

    abortRef.current?.abort();
    abortRef.current = new AbortController();
    try {
      const r = await fetch(`${API_BASE_URL}/eprod/cycle-start`, {
        method: 'POST', body: fd, signal: abortRef.current.signal,
        headers: { 'Accept': 'text/event-stream' },
      });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      await consumeStream(r);
    } catch (e: any) {
      if (e.name === 'AbortError') return;
      setErrorMsg(e.message ?? String(e));
      setRunning(false);
    }
  }, [consumeStream, reset]);

  const startWithSample = useCallback(async (sample: SampleFile) => {
    // Fetch the sample file and submit as multipart
    const r = await fetch(`${API_BASE_URL}/eprod/sample-file/${encodeURIComponent(sample.name)}`);
    if (!r.ok) { setErrorMsg(`Could not load sample: ${sample.name}`); return; }
    const blob = await r.blob();
    const file = new File([blob], sample.name, { type: blob.type || 'text/plain' });
    await startCycle(file);
  }, [startCycle]);

  const onDropFile = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file) startCycle(file);
  }, [startCycle]);

  // ─────────────── render ───────────────
  return (
    <>
      <Head><title>EPROD AP Cycle · Live Run | APEX</title></Head>
      <div style={{ background: '#f8fafc', minHeight: '100vh', padding: '24px 32px' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 22 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#94a3b8', letterSpacing: '.1em', textTransform: 'uppercase', marginBottom: 4 }}>
              <Link href="/canvas" style={{ color: '#94a3b8', textDecoration: 'none' }}>Canvas</Link>
              {' › '}
              <Link href="/canvas/playbook/pb-eprod-1" style={{ color: '#94a3b8', textDecoration: 'none' }}>Invoice Intelligence</Link>
            </div>
            <h1 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', margin: 0 }}>EPROD AP Cycle · Live Run</h1>
            <div style={{ fontSize: 12, color: '#64748b', marginTop: 4 }}>
              Drop a midstream document and watch all 6 agents process it end-to-end · audit-ready PDF on completion
            </div>
          </div>
          <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
            {cycleId && (
              <span style={pill('#f1f5f9', '#475569', '#e2e8f0')}>
                Cycle: <strong style={{ marginLeft: 4, fontFamily: "'JetBrains Mono', monospace" }}>{cycleId}</strong>
              </span>
            )}
            {running && (
              <span style={pill('#fffbeb', '#d97706', '#fde68a')}>
                <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#f59e0b', display: 'inline-block', animation: 'pulse 1s infinite', marginRight: 6 }} />
                Running
              </span>
            )}
            {!running && cycleReport && !halted && (
              <span style={pill('#f0fdf4', '#16a34a', '#bbf7d0')}>
                ✓ {cycleReport.status}
              </span>
            )}
            {halted && (
              <span style={pill('#fef2f2', '#dc2626', '#fecaca')}>
                ✗ Halted
              </span>
            )}
          </div>
        </div>

        {/* 2-column layout: left = sample picker / dropzone · right = live timeline */}
        <div style={{ display: 'grid', gridTemplateColumns: '380px 1fr', gap: 20 }}>

          {/* Left — input */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

            {/* Dropzone */}
            <div
              onDragOver={(e) => e.preventDefault()}
              onDrop={onDropFile}
              style={{
                ...card, padding: 24, textAlign: 'center', border: '2px dashed #cbd5e1',
                cursor: running ? 'not-allowed' : 'copy', opacity: running ? 0.5 : 1,
              }}
            >
              <div style={{ fontSize: 32, marginBottom: 6 }}>📥</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: '#0f172a' }}>Drop document here</div>
              <div style={{ fontSize: 11, color: '#64748b', marginTop: 4 }}>
                Invoice · PO · MSA · Quote · Tariff · JIB
              </div>
              <div style={{ fontSize: 10, color: '#94a3b8', marginTop: 8 }}>
                — or click a sample below —
              </div>
            </div>

            {/* Sample files list */}
            <div style={card}>
              <div style={{ padding: '14px 16px', borderBottom: '1px solid #e2e8f0' }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: '#0f172a' }}>Sample documents</div>
                <div style={{ fontSize: 10, color: '#64748b', marginTop: 1 }}>
                  {sampleFiles.length} files in synthetic-data/eprod/
                </div>
              </div>
              <div style={{ maxHeight: 540, overflowY: 'auto' }}>
                {sampleFiles.length === 0 && (
                  <div style={{ padding: 16, fontSize: 11, color: '#94a3b8', textAlign: 'center' }}>
                    No sample files available. Check that the backend is reachable.
                  </div>
                )}
                {sampleFiles.map((s) => (
                  <button
                    key={s.name}
                    onClick={() => !running && startWithSample(s)}
                    disabled={running}
                    style={{
                      display: 'flex', flexDirection: 'column', alignItems: 'flex-start',
                      width: '100%', textAlign: 'left',
                      padding: '10px 16px', background: 'transparent', border: 'none',
                      borderBottom: '1px solid #f1f5f9',
                      cursor: running ? 'not-allowed' : 'pointer',
                      opacity: running ? 0.4 : 1,
                    }}
                    onMouseOver={(e) => !running && (e.currentTarget.style.background = '#f8fafc')}
                    onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
                  >
                    <div style={{ fontSize: 11, fontWeight: 700, color: '#0f172a', fontFamily: "'JetBrains Mono', monospace" }}>
                      {s.name}
                    </div>
                    <div style={{ fontSize: 10, color: '#64748b', marginTop: 2 }}>
                      {DOC_TYPE_LABEL[s.doc_type] || s.doc_type} · {(s.size_bytes / 1024).toFixed(1)} KB
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {(running || cycleReport || halted) && (
              <button
                onClick={reset}
                disabled={running}
                style={{
                  padding: '10px 16px', borderRadius: 10,
                  background: '#f1f5f9', color: '#475569',
                  border: '1px solid #e2e8f0',
                  fontSize: 12, fontWeight: 700,
                  cursor: running ? 'not-allowed' : 'pointer',
                  opacity: running ? 0.5 : 1,
                }}
              >
                ↺ Reset
              </button>
            )}
          </div>

          {/* Right — timeline + findings + HITL + report */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

            {/* Stage timeline */}
            <div style={{ ...card, padding: 20 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#0f172a', marginBottom: 14 }}>
                Cycle Stages
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {stages.map((s, i) => (
                  <StageRow key={s.id} stage={s} index={i + 1} />
                ))}
              </div>
            </div>

            {/* HITL banner (conditional) */}
            {hitl && (
              <HitlBanner
                req={hitl} decision={hitlDecision} busy={hitlBusy}
                onApprove={() => decideHitl('approve')}
                onReject={() => decideHitl('reject')}
              />
            )}

            {/* Halted banner */}
            {halted && (
              <div style={{
                padding: 14, borderRadius: 10, background: '#fef2f2', border: '1px solid #fecaca',
                color: '#991b1b', fontSize: 12,
              }}>
                <strong>Cycle halted.</strong> {halted.reason}
              </div>
            )}

            {/* Findings */}
            {findings.length > 0 && (
              <div style={{ ...card, padding: 20 }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#0f172a', marginBottom: 12 }}>
                  Validation Findings · {findings.length}
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {findings.map((f, i) => (
                    <FindingRow key={i} finding={f} />
                  ))}
                </div>
              </div>
            )}

            {/* Final report card */}
            {cycleReport && (
              <FinalReportCard report={cycleReport} cycleId={cycleId} />
            )}

            {/* Error */}
            {errorMsg && (
              <div style={{
                padding: 14, borderRadius: 10, background: '#fef2f2', border: '1px solid #fecaca',
                color: '#991b1b', fontSize: 12,
              }}>
                <strong>Error:</strong> {errorMsg}
              </div>
            )}
          </div>
        </div>

        <style>{`
          @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
          @keyframes hitlPulse {
            0%,100% { box-shadow: 0 0 0 0 rgba(245,158,11,.0); }
            50%     { box-shadow: 0 0 0 4px rgba(245,158,11,.18); }
          }
        `}</style>
      </div>
    </>
  );
}

// ─────────────── sub-components ───────────────

const card: React.CSSProperties = {
  background: '#fff', borderRadius: 12, border: '1px solid #e2e8f0',
  boxShadow: '0 1px 3px rgba(0,0,0,.04)',
};

const pill = (bg: string, fg: string, bd: string): React.CSSProperties => ({
  display: 'inline-flex', alignItems: 'center',
  padding: '4px 10px', borderRadius: 99, fontSize: 11, fontWeight: 600,
  background: bg, color: fg, border: `1px solid ${bd}`,
});

const DOC_TYPE_LABEL: Record<string, string> = {
  invoice:           'Vendor invoice',
  purchase_order:    'Purchase order',
  msa:               'Master service agreement',
  engineering_quote: 'Engineering quote',
  tariff_sheet:      'FERC tariff sheet',
  jib_statement:     'JIB statement',
};

function StageRow({ stage, index }: { stage: StageState; index: number }) {
  const dotColor =
    stage.status === 'done'    ? '#16a34a' :
    stage.status === 'running' ? '#f59e0b' :
    stage.status === 'error'   ? '#dc2626' :
                                 '#cbd5e1';
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '8px 0' }}>
      <div style={{
        width: 24, height: 24, borderRadius: '50%',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        background: stage.status === 'done' ? '#dcfce7' : stage.status === 'running' ? '#fef3c7' : stage.status === 'error' ? '#fee2e2' : '#f1f5f9',
        color: dotColor, fontSize: 12, fontWeight: 700,
        animation: stage.status === 'running' ? 'pulse 1.5s infinite' : undefined,
        flexShrink: 0,
      }}>
        {stage.status === 'done' ? '✓' : stage.status === 'error' ? '✗' : index}
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontSize: 12, fontWeight: 700,
          color: stage.status === 'pending' ? '#94a3b8' : '#0f172a',
        }}>
          {stage.label}
          {stage.ms !== undefined && (
            <span style={{ marginLeft: 8, fontWeight: 400, color: '#94a3b8', fontFamily: "'JetBrains Mono', monospace" }}>
              {(stage.ms / 1000).toFixed(1)}s
            </span>
          )}
        </div>
        {stage.summary && (
          <div style={{ fontSize: 11, color: '#64748b', marginTop: 2 }}>{stage.summary}</div>
        )}
      </div>
    </div>
  );
}

function FindingRow({ finding }: { finding: Finding }) {
  const palette =
    finding.severity === 'critical' ? { bg: '#fef2f2', fg: '#b91c1c', bd: '#fecaca' } :
    finding.severity === 'high'     ? { bg: '#fff7ed', fg: '#c2410c', bd: '#fed7aa' } :
    finding.severity === 'medium'   ? { bg: '#fffbeb', fg: '#92400e', bd: '#fde68a' } :
                                      { bg: '#f0fdf4', fg: '#166534', bd: '#bbf7d0' };
  return (
    <div style={{
      padding: '10px 12px', borderRadius: 8,
      background: palette.bg, border: `1px solid ${palette.bd}`,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
        <span style={pill(palette.bg, palette.fg, palette.bd)}>{finding.severity}</span>
        {finding.category && (
          <span style={{ fontSize: 9, color: '#64748b', textTransform: 'uppercase', letterSpacing: '.06em' }}>
            {finding.category}
          </span>
        )}
      </div>
      <div style={{ fontSize: 12, fontWeight: 700, color: '#0f172a' }}>{finding.rule}</div>
      <div style={{ fontSize: 11, color: '#475569', marginTop: 2, lineHeight: 1.5 }}>{finding.detail}</div>
      {(finding.expected || finding.actual) && (
        <div style={{ fontSize: 10, color: '#64748b', marginTop: 4, fontFamily: "'JetBrains Mono', monospace" }}>
          {finding.expected && <>expected: {finding.expected}</>}
          {finding.expected && finding.actual && '  ·  '}
          {finding.actual && <>actual: {finding.actual}</>}
        </div>
      )}
    </div>
  );
}

function HitlBanner({ req, decision, busy, onApprove, onReject }: {
  req: HitlRequired;
  decision: HitlDecided | null;
  busy: boolean;
  onApprove: () => void;
  onReject:  () => void;
}) {
  if (decision) {
    const palette =
      decision.decision === 'approve' ? { bg: '#f0fdf4', fg: '#15803d', bd: '#bbf7d0' } :
      decision.decision === 'reject'  ? { bg: '#fef2f2', fg: '#b91c1c', bd: '#fecaca' } :
                                        { bg: '#f8fafc', fg: '#64748b', bd: '#e2e8f0' };
    return (
      <div style={{
        padding: 16, borderRadius: 12,
        background: palette.bg, border: `1px solid ${palette.bd}`,
      }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: palette.fg }}>
          HITL {decision.decision === 'approve' ? '✓ Approved' : decision.decision === 'reject' ? '✗ Rejected' : '⏱ Timed out'}
          {decision.reviewer && <span style={{ marginLeft: 10, fontWeight: 500, color: '#475569' }}>— {decision.reviewer}</span>}
        </div>
        {decision.comment && (
          <div style={{ fontSize: 11, color: '#475569', marginTop: 4 }}>{decision.comment}</div>
        )}
      </div>
    );
  }
  const palette = req.severity === 'critical' || req.severity === 'high'
    ? { bg: '#fef2f2', bd: '#fecaca', accent: '#dc2626' }
    : { bg: '#fffbeb', bd: '#fde68a', accent: '#d97706' };
  return (
    <div style={{
      padding: 18, borderRadius: 12, background: palette.bg,
      border: `2px solid ${palette.bd}`, animation: 'hitlPulse 2s ease-in-out infinite',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span style={{ fontSize: 22 }}>⚠</span>
        <div style={{ fontSize: 14, fontWeight: 800, color: palette.accent }}>
          HITL · {req.severity} severity · {req.agent}
        </div>
      </div>
      <div style={{ fontSize: 11, fontWeight: 600, color: '#475569', marginBottom: 6, fontFamily: "'JetBrains Mono', monospace" }}>
        Pipeline paused for human approval — {req.request_id}
      </div>
      <div style={{ fontSize: 12, color: '#0f172a', lineHeight: 1.55, marginBottom: 6 }}>
        <strong>Reason:</strong> {req.reason}
      </div>
      <div style={{ fontSize: 12, color: '#475569', lineHeight: 1.55, marginBottom: 14 }}>
        <strong>Proposed action:</strong> {req.proposed_action}
      </div>
      <div style={{ display: 'flex', gap: 10 }}>
        <button
          onClick={onApprove}
          disabled={busy}
          style={{
            flex: 1, padding: '10px 16px', borderRadius: 10,
            background: '#16a34a', color: '#fff', border: 'none',
            fontSize: 12, fontWeight: 700,
            cursor: busy ? 'not-allowed' : 'pointer', opacity: busy ? 0.5 : 1,
          }}
        >
          {busy ? '...' : '✓ Approve — proceed with write-back'}
        </button>
        <button
          onClick={onReject}
          disabled={busy}
          style={{
            flex: 1, padding: '10px 16px', borderRadius: 10,
            background: '#dc2626', color: '#fff', border: 'none',
            fontSize: 12, fontWeight: 700,
            cursor: busy ? 'not-allowed' : 'pointer', opacity: busy ? 0.5 : 1,
          }}
        >
          {busy ? '...' : '✗ Reject — halt pipeline'}
        </button>
      </div>
    </div>
  );
}

function FinalReportCard({ report, cycleId }: { report: CycleReport; cycleId: string | null }) {
  const pdfUrl = report.report_pdf_url
    || (cycleId ? `${API_BASE_URL}/eprod/report/${encodeURIComponent(cycleId)}` : null);
  return (
    <div style={{ ...card, padding: 22, borderLeft: '4px solid #047857' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14 }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 700, color: '#047857', letterSpacing: '.1em', textTransform: 'uppercase' }}>
            AP Cycle Audit Report
          </div>
          <div style={{ fontSize: 17, fontWeight: 800, color: '#0f172a', marginTop: 4 }}>
            {report.report_id}
          </div>
        </div>
        {pdfUrl && (
          <a
            href={pdfUrl}
            target="_blank" rel="noopener noreferrer"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              padding: '10px 16px', borderRadius: 10,
              background: '#047857', color: '#fff',
              fontSize: 12, fontWeight: 700, textDecoration: 'none',
            }}
          >
            📄 Download PDF
          </a>
        )}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginBottom: 14 }}>
        <ReportKpi label="Doc type"      value={DOC_TYPE_LABEL[report.doc_type] || report.doc_type} />
        <ReportKpi label="Status"        value={report.status} color={
          report.status.toUpperCase().includes('HALT') || report.status.toUpperCase().includes('REJECT') ? '#dc2626' :
          report.status.toUpperCase().includes('HITL') ? '#d97706' :
          '#047857'
        } />
        <ReportKpi label="Vendor"        value={report.vendor || '—'} />
        <ReportKpi label="Amount"        value={report.amount ? `$${report.amount.toLocaleString()}` : '—'} />
      </div>
      <div style={{ display: 'flex', gap: 16, fontSize: 11, color: '#475569', borderTop: '1px solid #f1f5f9', paddingTop: 12 }}>
        <div>Findings: <strong style={{ color: '#0f172a' }}>{report.findings_count}</strong></div>
        <div>HITL: <strong style={{ color: '#0f172a' }}>{report.hitl_required ? `Yes (${report.hitl_decision ?? '—'})` : 'No'}</strong></div>
        {report.audit_lens_event_id && (
          <div>Audit: <strong style={{ color: '#0f172a', fontFamily: "'JetBrains Mono', monospace" }}>{report.audit_lens_event_id}</strong></div>
        )}
      </div>
    </div>
  );
}

function ReportKpi({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <div>
      <div style={{ fontSize: 9, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '.08em' }}>{label}</div>
      <div style={{ fontSize: 14, fontWeight: 800, color: color || '#0f172a', marginTop: 2 }}>{value}</div>
    </div>
  );
}
