"""
Shared utilities for nuclear_operations action handlers.

All handlers in this package read from the synthetic-data corpus generated by
`synthetic-data/nuclear_operations/generate.py`. The synthetic data may not
exist yet during early development — these helpers degrade gracefully and
return a uniform error envelope so handlers can short-circuit cleanly.

Cached loaders (LRU) keep warm-container invocations under a few hundred
microseconds after the first read.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------

# actions/nuclear_operations/_shared.py -> parents[2] is aws/
_AWS_ROOT = Path(__file__).resolve().parents[2]
_DATA_ROOT = _AWS_ROOT / "synthetic-data" / "nuclear_operations"


def data_path(*parts: str) -> Path:
    """Build an absolute path under synthetic-data/nuclear_operations/."""
    # Allow override via env var for tests / alternate corpora.
    override = os.environ.get("APEX_NUCLEAR_DATA_DIR")
    base = Path(override).resolve() if override else _DATA_ROOT
    return base.joinpath(*parts)


# ---------------------------------------------------------------------------
# Error envelope
# ---------------------------------------------------------------------------

def missing_data_envelope(missing: str) -> Dict[str, Any]:
    """Uniform envelope returned when a required synthetic-data file is missing.

    Args:
        missing: Path or filename that was expected but not found.

    Returns:
        Standard error dict with status, error_type, message, missing_path.
    """
    return {
        "status": "error",
        "error_type": "synthetic_data_not_generated",
        "message": "Run synthetic-data/nuclear_operations/generate.py first",
        "missing_path": str(missing),
    }


def not_found_envelope(resource: str, identifier: str) -> Dict[str, Any]:
    """Envelope returned when a referenced record/file legitimately does not exist."""
    return {
        "status": "not_found",
        "resource": resource,
        "identifier": identifier,
        "message": f"{resource} '{identifier}' was not found in the corpus",
    }


# ---------------------------------------------------------------------------
# Cached JSON loaders
# ---------------------------------------------------------------------------

def _read_json(path: Path) -> Optional[Any]:
    """Read a JSON file. Returns None if missing or unparseable."""
    try:
        if not path.exists():
            return None
        with path.open("r", encoding="utf-8") as fp:
            return json.load(fp)
    except (OSError, json.JSONDecodeError):
        return None


@lru_cache(maxsize=1)
def _cache_key() -> str:
    """Cache invalidator. Tests can clear the LRU caches by calling clear_caches()."""
    return os.environ.get("APEX_NUCLEAR_DATA_DIR", "default")


def clear_caches() -> None:
    """Clear all module-scoped caches. Used by tests via monkeypatch."""
    load_work_orders.cache_clear()
    load_personnel.cache_clear()
    load_change_history.cache_clear()
    load_failure_events.cache_clear()
    load_failure_mode_catalog.cache_clear()
    load_equipment.cache_clear()
    load_pm_schedule.cache_clear()
    load_seed_anomalies.cache_clear()
    _cache_key.cache_clear()


@lru_cache(maxsize=1)
def load_work_orders() -> Optional[List[Dict[str, Any]]]:
    """Load work_orders.json. Returns None if missing."""
    _ = _cache_key()  # tie cache to env override
    return _read_json(data_path("work_orders.json"))


@lru_cache(maxsize=1)
def load_personnel() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("personnel.json"))


@lru_cache(maxsize=1)
def load_change_history() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("change_history.json"))


@lru_cache(maxsize=1)
def load_failure_events() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("failure_events.json"))


@lru_cache(maxsize=1)
def load_failure_mode_catalog() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("failure_mode_catalog.json"))


@lru_cache(maxsize=1)
def load_equipment() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("equipment.json"))


@lru_cache(maxsize=1)
def load_pm_schedule() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("pm_schedule.json"))


@lru_cache(maxsize=1)
def load_seed_anomalies() -> Optional[List[Dict[str, Any]]]:
    _ = _cache_key()
    return _read_json(data_path("seed_anomalies.json"))


# ---------------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------------

def parse_date(value: Any) -> Optional[datetime]:
    """Best-effort ISO-8601 / common-date parser. Returns None on failure."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    s = str(value).strip()
    if not s:
        return None
    # Try a few common formats
    for fmt in ("%Y-%m-%dT%H:%M:%S", "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d %H:%M:%S",
                "%Y-%m-%d", "%m/%d/%Y", "%m-%d-%Y"):
        try:
            return datetime.strptime(s[: len(fmt) + 5], fmt)
        except (ValueError, TypeError):
            continue
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def days_between(a: Any, b: Any) -> Optional[int]:
    """Whole-day delta between two parseable dates. None if either fails."""
    da, db = parse_date(a), parse_date(b)
    if da is None or db is None:
        return None
    return (db - da).days


def within_window(when: Any, *, days: int, reference: Optional[datetime] = None) -> bool:
    """Return True if `when` is within `days` days before `reference` (default: now)."""
    ref = reference or datetime.utcnow()
    parsed = parse_date(when)
    if parsed is None:
        return False
    return ref - timedelta(days=days) <= parsed <= ref


# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------

def filter_by_field(rows: List[Dict[str, Any]], field: str, value: Any) -> List[Dict[str, Any]]:
    """Return subset of `rows` where row[field] == value."""
    return [r for r in rows if r.get(field) == value]


def index_by(rows: List[Dict[str, Any]], field: str) -> Dict[Any, Dict[str, Any]]:
    """Build a {field_value: row} index. Last write wins on duplicates."""
    return {r.get(field): r for r in rows if r.get(field) is not None}
