"""
jira_create_ticket — Create a single JIRA Cloud issue.

Reads classified failures (or any single failure dict) from the cycle
orchestrator and opens one JIRA ticket per call. Used heavily by the
CertificationAgent pipeline at Step 4 (after classify_failures).

Configuration (env, see backend/services/jira_client.py docstring):
  JIRA_URL, JIRA_EMAIL, JIRA_TOKEN, JIRA_PROJECT_KEY, JIRA_MOCK_MODE

When credentials are missing or JIRA_MOCK_MODE=true, returns realistic
mock responses so the demo runs end-to-end without a JIRA account.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.append(str(Path(__file__).resolve().parents[3]))
sys.path.append(str(Path(__file__).resolve().parents[3] / "backend"))

from actions.sdk import apex_action, ApexActionSchema, ActionInputSchema, ActionOutputSchema  # noqa: E402
from services.jira_client import get_client  # noqa: E402


# Team auto-assign matrix — keyed off classify_failures categories.
# Override per-call via the `assignee_team` arg.
TEAM_LABELS: Dict[str, str] = {
    "latency_threshold_breach": "vendor-engineering",
    "schema_drift_failure":     "automation-team",
    "regression_failure":       "cert-team",
    "investigate":              "cert-team",
}


def _compose_description(failure: Dict[str, Any]) -> str:
    """Build a human-readable description body from a classified failure."""
    lines: List[str] = []
    summary = failure.get("summary") or failure.get("test_name") or ""
    if summary:
        lines.append(summary)
        lines.append("")  # paragraph break

    if failure.get("root_cause"):
        lines.append(f"Root cause: {failure['root_cause']}")
        lines.append("")
    if failure.get("recommendation"):
        lines.append(f"Recommendation: {failure['recommendation']}")
        lines.append("")
    if failure.get("kb_match"):
        lines.append(f"Linked KB: {failure['kb_match']}")
    if failure.get("redfish_endpoint"):
        lines.append(f"Redfish endpoint: {failure['redfish_endpoint']}")
    if failure.get("test_case_id"):
        lines.append(f"Test case: {failure['test_case_id']}")
    if failure.get("cycle_id"):
        lines.append(f"Cycle: {failure['cycle_id']}")

    lines.append("")
    lines.append("Generated by APEX CertificationAgent. "
                 "Do not close without APEX review.")
    return "\n".join(lines)


@apex_action(ApexActionSchema(
    name="jira_create_ticket",
    description="Create a single JIRA Cloud issue from a classified failure. "
                "Auto-applies team labels + apex-auto-generated label. Falls "
                "back to mock mode when JIRA env vars are missing.",
    category="integration",
    industry="core",
    input_schema=ActionInputSchema(description="One classified failure")
        .add_string("summary",          "Ticket summary (one-line title)", required=True)
        .add_string("description",      "Body text (markdown-ish); paragraphs split on blank lines")
        .add_string("severity",         "P1 | P2 | P3 — prepended to summary if not already there")
        .add_string("category",         "Classification category (latency_threshold_breach / schema_drift_failure / regression_failure / investigate)")
        .add_string("assignee_team",    "Override the default team label")
        .add_string("parent_epic_key",  "JIRA key of parent epic for schema-drift bundles")
        .add_string("test_case_id",     "ROBOT test id (e.g. s2-t1)")
        .add_string("redfish_endpoint", "Redfish endpoint path if relevant")
        .add_string("root_cause",       "Root cause hypothesis from CertificationAgent")
        .add_string("recommendation",   "Recommended remediation")
        .add_string("kb_match",         "Linked KB id, e.g. KB-2026-0118")
        .add_string("cycle_id",         "Source certification cycle id"),
    output_schema=ActionOutputSchema(description="Created JIRA ticket reference")
        .add_string("status",       "ok | error")
        .add_string("ticket_key",   "JIRA key, e.g. APEXVZ-2418")
        .add_string("ticket_url",   "Direct browse URL")
        .add_string("mock",         "True if mock-mode response (no live JIRA call)")
        .add_string("http_status",  "JIRA HTTP status code on the create call (null on mock or network error)")
        .add_string("error",        "Error detail if status=error"),
))
def jira_create_ticket(
    *,
    summary: str,
    description: str = "",
    severity: Optional[str] = None,
    category: Optional[str] = None,
    assignee_team: Optional[str] = None,
    parent_epic_key: Optional[str] = None,
    test_case_id: Optional[str] = None,
    redfish_endpoint: Optional[str] = None,
    root_cause: Optional[str] = None,
    recommendation: Optional[str] = None,
    kb_match: Optional[str] = None,
    cycle_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Open one JIRA issue and return its key+url."""
    if not summary:
        return {"status": "error", "error": "summary is required"}

    # Compose final summary with [SEV] prefix if not already there.
    final_summary = summary
    if severity and not summary.startswith("["):
        final_summary = f"[{severity}] {summary}"

    # Build a structured description if the caller passed a failure dict
    # via shorthand fields. If the caller already provided `description`,
    # honor it as-is.
    if not description:
        description = _compose_description({
            "summary":          summary,
            "test_case_id":     test_case_id,
            "redfish_endpoint": redfish_endpoint,
            "root_cause":       root_cause,
            "recommendation":   recommendation,
            "kb_match":         kb_match,
            "cycle_id":         cycle_id,
        })

    # Labels: severity + team + category + cycle.
    labels: List[str] = ["far-edge", "certification"]
    if severity:
        labels.append(severity.lower())
    if category:
        team = assignee_team or TEAM_LABELS.get(category, "cert-team")
        labels.append(f"team-{team}")
        labels.append(category.replace("_", "-"))
    elif assignee_team:
        labels.append(f"team-{assignee_team}")
    if cycle_id:
        labels.append(f"cycle-{cycle_id}")
    if kb_match:
        labels.append(f"kb-{kb_match}")

    # Issue type defaults to "Task" because the SCRUM template (and many
    # Atlassian free-tier defaults) doesn't enable "Bug" out of the box.
    # If the project doesn't have Task either, override via env:
    #   JIRA_DEFAULT_ISSUE_TYPE=Story (or whatever IS allowed)
    import os
    issue_type = os.environ.get("JIRA_DEFAULT_ISSUE_TYPE", "Task").strip() or "Task"

    client = get_client()
    result = client.create_issue(
        summary=final_summary,
        description=description,
        issue_type=issue_type,
        labels=labels,
        parent_epic_key=parent_epic_key,
    )

    if result.get("key"):
        return {
            "status":      "ok",
            "ticket_key":  result["key"],
            "ticket_url":  result["url"],
            "mock":        result.get("mock", False),
            "http_status": result.get("http_status"),
            "error":       None,
        }
    return {
        "status":      "error",
        "ticket_key":  None,
        "ticket_url":  None,
        "mock":        result.get("mock", False),
        "http_status": result.get("http_status"),
        "error":       result.get("raw_error", "unknown JIRA error"),
    }
