#!/usr/bin/env python3
"""
Train + deploy the 4 ApexSignal SageMaker endpoints onto AWS us-east-1.

Per ApexSignal_ClaudeCode_Spec.docx §2 + Apex_Master_Implementation_Spec.docx §3.3:

  apex-signal-lead-time   — XGBoost binary classification (PO delay risk)
  apex-signal-supplier    — XGBoost multi-class (Very Low / Low / Medium / High / Critical)
  apex-signal-stockout    — Linear Learner regression (days_until_stockout)
  apex-signal-demand      — DeepAR time-series (weekly units_sold forecast)

Training data was pre-generated by synthetic-data/supply-chain/generate.py and
uploaded to s3://apex-ml-training-data-457795063704/supply-chain/.

Runs sequentially so any training failure halts before the next model burns
compute. Emits endpoint ARNs at the end for pasting into the backend config.

IMPORTANT · cost control:
  Each ml.m5.large endpoint is ~$0.10/hr. 4 endpoints running continuously is
  ~$10/day. Tear them down with `python3 deploy_sagemaker_endpoints.py --destroy`
  when not needed for the CBB demo.
"""

from __future__ import annotations

import argparse
import io
import os
import sys
from datetime import datetime, timezone

import boto3
import pandas as pd
import sagemaker
from sagemaker import image_uris, Session
from sagemaker.estimator import Estimator
from sagemaker.inputs import TrainingInput

REGION = "us-east-1"
ACCOUNT_ID = "457795063704"
ROLE_ARN = f"arn:aws:iam::{ACCOUNT_ID}:role/service-role/AmazonSageMaker-ExecutionRole-20260114T081145"

TRAIN_BUCKET = "apex-ml-training-data-457795063704"
MODEL_BUCKET = "apex-ml-models-457795063704"
PREFIX = "supply-chain"

INSTANCE_TYPE = "ml.m5.large"
INSTANCE_COUNT = 1

# Endpoint names the backend expects.
ENDPOINTS = {
    "lead_time": "apex-signal-lead-time",
    "supplier":  "apex-signal-supplier",
    "stockout":  "apex-signal-stockout",
    "demand":    "apex-signal-demand",
}

s3 = boto3.client("s3", region_name=REGION)
sm = boto3.client("sagemaker", region_name=REGION)
sess = Session(boto3.session.Session(region_name=REGION))


# ──────────────────────────── dataset prep ────────────────────────────

def _fetch_csv(key: str) -> pd.DataFrame:
    """Load a CSV from the supply-chain training prefix."""
    obj = s3.get_object(Bucket=TRAIN_BUCKET, Key=f"{PREFIX}/{key}")
    return pd.read_csv(io.BytesIO(obj["Body"].read()))


def _fetch_json(key: str):
    """Load a JSON file from the supply-chain training prefix."""
    import json as _json
    obj = s3.get_object(Bucket=TRAIN_BUCKET, Key=f"{PREFIX}/{key}")
    return _json.loads(obj["Body"].read())


def _put_csv(df: pd.DataFrame, key: str, include_header: bool = False) -> str:
    """Write a CSV back to S3 in the shape SageMaker wants (label first column, no header)."""
    buf = io.StringIO()
    df.to_csv(buf, index=False, header=include_header)
    s3.put_object(Bucket=TRAIN_BUCKET, Key=key, Body=buf.getvalue().encode())
    return f"s3://{TRAIN_BUCKET}/{key}"


def prep_lead_time_training_data() -> tuple[str, str]:
    """Build training CSV for XGBoost binary: predict po.delay_days > 0.

    Features: supplier_on_time_pct, supplier_lead_time_avg, supplier_risk_numeric,
              qty, origin_port_encoded.
    Label: delayed (0|1).
    """
    po_df  = pd.DataFrame(_fetch_json("purchase_orders.json"))
    sup_df = pd.DataFrame(_fetch_json("suppliers.json"))

    # Keep only received rows (actual vs promised known)
    hist = po_df[po_df["status"] == "received"].copy()
    hist = hist.merge(sup_df[["supplier_id", "on_time_pct", "lead_time_days_avg", "risk_score"]], on="supplier_id")

    risk_num = {"Very Low": 1, "Low": 2, "Medium": 3, "High": 4, "Critical": 5}
    hist["risk_numeric"] = hist["risk_score"].map(risk_num).fillna(3)
    port_ix = {p: i for i, p in enumerate(sorted(hist["origin_port"].unique()))}
    hist["port_enc"] = hist["origin_port"].map(port_ix)
    hist["delayed"]  = (hist["delay_days"] > 0).astype(int)

    cols = ["delayed", "on_time_pct", "lead_time_days_avg", "risk_numeric", "qty", "port_enc"]
    split = max(1, int(len(hist) * 0.8))
    train_uri = _put_csv(hist[cols].iloc[:split], f"{PREFIX}/lead_time/train.csv")
    val_uri   = _put_csv(hist[cols].iloc[split:], f"{PREFIX}/lead_time/validation.csv")
    return train_uri, val_uri


def prep_supplier_risk_training_data() -> tuple[str, str]:
    """XGBoost multi-class on QC records.

    Features: moisture_pct, purity_pct, viscosity
    Label: risk_label index (0..4)
    """
    qc = _fetch_csv("qc_records.csv")
    label_ix = {"Very Low": 0, "Low": 1, "Medium": 2, "High": 3, "Critical": 4}
    qc["label"] = qc["risk_label"].map(label_ix).fillna(1).astype(int)
    cols = ["label", "moisture_pct", "purity_pct", "viscosity"]
    split = max(1, int(len(qc) * 0.8))
    train_uri = _put_csv(qc[cols].iloc[:split], f"{PREFIX}/supplier/train.csv")
    val_uri   = _put_csv(qc[cols].iloc[split:], f"{PREFIX}/supplier/validation.csv")
    return train_uri, val_uri


def prep_stockout_training_data() -> str:
    """Linear Learner regression on inventory_bom.json + demand_history.csv.

    Features: stock_level, burn_rate_per_day, safety_stock_pct,
              avg_weekly_demand_for_this_region, trend_delta.
    Label: days_remaining (continuous).
    """
    inv_bom = _fetch_json("inventory_bom.json")
    inv_df = pd.DataFrame(inv_bom["inventory"])
    demand_df = _fetch_csv("demand_history.csv")
    # Simple regional demand aggregate: join by plant-region (we don't have it
    # in inventory, so approximate via region_avg = mean units_sold across all
    # products/regions — good enough for a demo linear fit).
    region_avg = demand_df.groupby("region")["units_sold"].mean().to_dict()

    plants = {p["plant_id"]: p["region"] for p in inv_bom["plants"]}
    inv_df["region"] = inv_df["plant_id"].map(plants)
    inv_df["region_demand_avg"] = inv_df["region"].map(region_avg).fillna(3500)

    inv_df["trend_delta"] = (inv_df["burn_rate_per_day"] - inv_df["burn_rate_per_day"].mean())

    cols = ["days_remaining", "stock_level_kg", "burn_rate_per_day", "safety_stock_pct", "region_demand_avg", "trend_delta"]
    # Augment the 10-row inventory with jittered clones to give linear-learner enough signal
    import numpy as np
    rng = np.random.default_rng(42)
    augmented = pd.concat([inv_df[cols]] * 30, ignore_index=True)
    for c in ["stock_level_kg", "burn_rate_per_day", "safety_stock_pct", "region_demand_avg"]:
        augmented[c] = (augmented[c] * rng.uniform(0.85, 1.15, len(augmented))).round(1)
    augmented["days_remaining"] = (augmented["stock_level_kg"] / augmented["burn_rate_per_day"]).round(1)

    # Linear learner wants label first, no header.
    train_uri = _put_csv(augmented, f"{PREFIX}/stockout/train.csv")
    return train_uri


def prep_demand_training_data() -> str:
    """DeepAR needs JSON Lines — one line per time series, with start + target array."""
    d = _fetch_csv("demand_history.csv")
    d["week_start"] = pd.to_datetime(d["week_start"])

    lines = []
    for (product_id, region), g in d.groupby(["product_id", "region"]):
        g = g.sort_values("week_start")
        # Keep the series minimal — DeepAR accepts just start + target.
        series = {
            "start":  g["week_start"].min().strftime("%Y-%m-%d 00:00:00"),
            "target": g["units_sold"].astype(float).tolist(),
        }
        lines.append(series)

    # Split 80/20 for training/testing
    split = int(len(lines) * 0.8)
    import json as _json
    def _write(objs, key):
        body = "\n".join(_json.dumps(o) for o in objs).encode()
        s3.put_object(Bucket=TRAIN_BUCKET, Key=key, Body=body)
        return f"s3://{TRAIN_BUCKET}/{key}"
    train_uri = _write(lines[:split], f"{PREFIX}/demand/train/train.jsonl")
    test_uri  = _write(lines[split:], f"{PREFIX}/demand/test/test.jsonl")
    return train_uri, test_uri


# ──────────────────────────── per-endpoint pipelines ────────────────────────────

def train_and_deploy_xgboost_binary():
    print("\n── [1/4] apex-signal-lead-time · XGBoost (binary) ──")
    train_uri, val_uri = prep_lead_time_training_data()
    img = image_uris.retrieve("xgboost", REGION, version="1.7-1")
    est = Estimator(
        image_uri=img,
        role=ROLE_ARN,
        instance_count=INSTANCE_COUNT,
        instance_type=INSTANCE_TYPE,
        output_path=f"s3://{MODEL_BUCKET}/lead_time/",
        sagemaker_session=sess,
    )
    est.set_hyperparameters(objective="binary:logistic", num_round=60, eval_metric="error", max_depth=4, eta=0.15)
    est.fit({
        "train":      TrainingInput(train_uri, content_type="text/csv"),
        "validation": TrainingInput(val_uri,   content_type="text/csv"),
    }, wait=True, logs=False)
    predictor = est.deploy(
        endpoint_name=ENDPOINTS["lead_time"],
        initial_instance_count=1,
        instance_type=INSTANCE_TYPE,
        serializer=None, deserializer=None,
    )
    print(f"  ✓ deployed: {predictor.endpoint_name}")


def train_and_deploy_xgboost_multi():
    print("\n── [2/4] apex-signal-supplier · XGBoost (multi-class) ──")
    train_uri, val_uri = prep_supplier_risk_training_data()
    img = image_uris.retrieve("xgboost", REGION, version="1.7-1")
    est = Estimator(
        image_uri=img,
        role=ROLE_ARN,
        instance_count=INSTANCE_COUNT,
        instance_type=INSTANCE_TYPE,
        output_path=f"s3://{MODEL_BUCKET}/supplier/",
        sagemaker_session=sess,
    )
    est.set_hyperparameters(objective="multi:softprob", num_class=5, num_round=60, max_depth=4, eta=0.18)
    est.fit({
        "train":      TrainingInput(train_uri, content_type="text/csv"),
        "validation": TrainingInput(val_uri,   content_type="text/csv"),
    }, wait=True, logs=False)
    est.deploy(
        endpoint_name=ENDPOINTS["supplier"],
        initial_instance_count=1,
        instance_type=INSTANCE_TYPE,
    )
    print(f"  ✓ deployed: {ENDPOINTS['supplier']}")


def train_and_deploy_linear_learner():
    print("\n── [3/4] apex-signal-stockout · Linear Learner (regression) ──")
    train_uri = prep_stockout_training_data()
    img = image_uris.retrieve("linear-learner", REGION)
    est = Estimator(
        image_uri=img,
        role=ROLE_ARN,
        instance_count=INSTANCE_COUNT,
        instance_type=INSTANCE_TYPE,
        output_path=f"s3://{MODEL_BUCKET}/stockout/",
        sagemaker_session=sess,
    )
    est.set_hyperparameters(predictor_type="regressor", feature_dim=5, mini_batch_size=10, epochs=20, normalize_data="true", normalize_label="false")
    est.fit({
        "train": TrainingInput(train_uri, content_type="text/csv"),
    }, wait=True, logs=False)
    est.deploy(
        endpoint_name=ENDPOINTS["stockout"],
        initial_instance_count=1,
        instance_type=INSTANCE_TYPE,
    )
    print(f"  ✓ deployed: {ENDPOINTS['stockout']}")


def train_and_deploy_deepar():
    print("\n── [4/4] apex-signal-demand · DeepAR (time-series) ──")
    train_uri, test_uri = prep_demand_training_data()
    img = image_uris.retrieve("forecasting-deepar", REGION)
    est = Estimator(
        image_uri=img,
        role=ROLE_ARN,
        instance_count=INSTANCE_COUNT,
        instance_type=INSTANCE_TYPE,
        output_path=f"s3://{MODEL_BUCKET}/demand/",
        sagemaker_session=sess,
    )
    est.set_hyperparameters(
        time_freq="W",
        epochs=15,
        prediction_length=12,
        context_length=12,
        num_cells=40,
        num_layers=2,
        likelihood="gaussian",
        mini_batch_size=8,
    )
    est.fit({
        "train": TrainingInput(train_uri, content_type="json"),
        "test":  TrainingInput(test_uri,  content_type="json"),
    }, wait=True, logs=False)
    est.deploy(
        endpoint_name=ENDPOINTS["demand"],
        initial_instance_count=1,
        instance_type=INSTANCE_TYPE,
    )
    print(f"  ✓ deployed: {ENDPOINTS['demand']}")


def destroy_all():
    for name in ENDPOINTS.values():
        try:
            sm.delete_endpoint(EndpointName=name); print(f"  ✓ deleted endpoint {name}")
        except sm.exceptions.ClientError as e:
            print(f"  [skip] endpoint {name}: {e.response['Error'].get('Message')}")
        # Config + model share the endpoint name in our setup
        for op in (sm.delete_endpoint_config, sm.delete_model):
            try:
                op(EndpointConfigName=name) if op == sm.delete_endpoint_config else op(ModelName=name)
            except Exception:
                pass


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", choices=["lead_time", "supplier", "stockout", "demand", "all"], default="all")
    parser.add_argument("--destroy", action="store_true")
    args = parser.parse_args()

    if args.destroy:
        print("Destroying all ApexSignal SageMaker endpoints …")
        destroy_all()
        return 0

    pipeline = {
        "lead_time": train_and_deploy_xgboost_binary,
        "supplier":  train_and_deploy_xgboost_multi,
        "stockout":  train_and_deploy_linear_learner,
        "demand":    train_and_deploy_deepar,
    }
    targets = [args.only] if args.only != "all" else list(pipeline)

    t0 = datetime.now(timezone.utc)
    print(f"Region: {REGION}  ·  Role: {ROLE_ARN.split('/')[-1]}")
    print(f"Training bucket: s3://{TRAIN_BUCKET}/{PREFIX}/  ·  Model bucket: s3://{MODEL_BUCKET}/")
    for t in targets:
        pipeline[t]()
    elapsed = (datetime.now(timezone.utc) - t0).total_seconds()
    print(f"\nAll endpoints deployed · {elapsed:.0f}s total\n")
    for key, name in ENDPOINTS.items():
        arn = f"arn:aws:sagemaker:{REGION}:{ACCOUNT_ID}:endpoint/{name}"
        print(f"  {key:10s} → {arn}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
